name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Prepare stuff
        run: |
          mkdir -p ~/go/bin
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: Get source
        run: |
          export PATH=~/go/bin:$PATH
          export GOPATH=~/go/
          go get github.com/e-minguez/file-to-machineconfig

      - name: Get dependencies
        run: |
          export PATH=~/go/bin:$PATH
          export GOPATH=~/go/
          cd ${GOPATH}/src/github.com/e-minguez/file-to-machineconfig
          make deps
      
      - name: Build
        run: |
          export PATH=~/go/bin:$PATH
          export GOPATH=~/go/
          cd ${GOPATH}/src/github.com/e-minguez/file-to-machineconfig
          make build

      - name: Test
        run: |
          export PATH=~/go/bin:$PATH
          export GOPATH=~/go/
          cd ${GOPATH}/src/github.com/e-minguez/file-to-machineconfig
          make test