name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Prepare stuff
        run: |
          mkdir -p ~/go/bin
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

      - name: Get dependencies
        run: |
          export PATH=~/go/bin:$PATH
          make deps
      
      - name: Build
        run: |
          export PATH=~/go/bin:$PATH
          make build

      - name: Test
        run: |
          export PATH=~/go/bin:$PATH
          make test